import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding the database...");

  const modes = await prisma.mode.createMany({
    data: [{ title: "Classic" }, { title: "Chrono" }, { title: "Xtreme" }],
    skipDuplicates: true,
  });

  console.log("✅ Seeded game modes!");

  const players = await prisma.player.createMany({
    data: [{ pseudo: "Strayerz" }, { pseudo: "Nec" }],
    skipDuplicates: true,
  });

  console.log("✅ Seeded players Nec & Strayerz!");

  const games = await prisma.game.createMany({
    data: [
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 2, authorId: 1 },
      { modeId: 1, authorId: 1 },
      { modeId: 1, authorId: 1 },
    ],
    skipDuplicates: true,
  });

  console.log(`✅ Seeded ${games.count} games!`);

  const scores = await prisma.score.createMany({
    data: [
      {
        playerId: 1,
        gameId: 1,
        guild: 6,
        dragons: 18,
        endGame: 13,
        eggs: 5,
        resources: 0,
        cards: 11,
        objectives: 18,
        misc: 2,
      },
      {
        playerId: 2,
        gameId: 1,
        guild: 20,
        dragons: 35,
        endGame: 11,
        eggs: 7,
        resources: 6,
        cards: 15,
        objectives: 19,
        misc: 1,
      },
      {
        playerId: 1,
        gameId: 2,
        guild: 6,
        dragons: 43,
        endGame: 20,
        eggs: 6,
        resources: 5,
        cards: 25,
        objectives: 16,
        misc: 1,
      },
      {
        playerId: 2,
        gameId: 2,
        guild: 12,
        dragons: 33,
        endGame: 0,
        eggs: 8,
        resources: 9,
        cards: 9,
        objectives: 19,
        misc: 2,
      },
      {
        playerId: 1,
        gameId: 3,
        guild: 10,
        dragons: 42,
        endGame: 18,
        eggs: 7,
        resources: 1,
        cards: 18,
        objectives: 16,
        misc: 1,
      },
      {
        playerId: 2,
        gameId: 3,
        guild: 16,
        dragons: 42,
        endGame: 15,
        eggs: 7,
        resources: 0,
        cards: 6,
        objectives: 19,
        misc: 0,
      },
      {
        playerId: 1,
        gameId: 4,
        guild: 14,
        dragons: 43,
        endGame: 0,
        eggs: 12,
        resources: 16,
        cards: 6,
        objectives: 22,
        misc: 2,
      },
      {
        playerId: 2,
        gameId: 4,
        guild: 18,
        dragons: 37,
        endGame: 22,
        eggs: 4,
        resources: 2,
        cards: 7,
        objectives: 13,
        misc: 1,
      },
      {
        playerId: 1,
        gameId: 5,
        guild: 3,
        dragons: 39,
        endGame: 9,
        eggs: 4,
        resources: 0,
        cards: 14,
        objectives: 16,
        misc: 1,
      },
      {
        playerId: 2,
        gameId: 5,
        guild: 18,
        dragons: 34,
        endGame: 5,
        eggs: 16,
        resources: 14,
        cards: 1,
        objectives: 22,
        misc: 1,
      },
      {
        playerId: 1,
        gameId: 6,
        guild: 3,
        dragons: 40,
        endGame: 8,
        eggs: 10,
        resources: 9,
        cards: 8,
        objectives: 19,
        misc: 1,
      },
      {
        playerId: 2,
        gameId: 6,
        guild: 15,
        dragons: 41,
        endGame: 11,
        eggs: 5,
        resources: 4,
        cards: 15,
        objectives: 19,
        misc: 4,
      },
      {
        playerId: 1,
        gameId: 7,
        guild: 8,
        dragons: 29,
        endGame: 0,
        eggs: 16,
        resources: 6,
        cards: 8,
        objectives: 15,
        misc: 2,
      },
      {
        playerId: 2,
        gameId: 7,
        guild: 6,
        dragons: 39,
        endGame: 17,
        eggs: 6,
        resources: 13,
        cards: 4,
        objectives: 22,
        misc: 0,
      },
      {
        playerId: 1,
        gameId: 8,
        guild: 10,
        dragons: 57,
        endGame: 8,
        eggs: 18,
        resources: 3,
        cards: 14,
        objectives: 19,
        misc: 2,
      },
      {
        playerId: 2,
        gameId: 8,
        guild: 9,
        dragons: 37,
        endGame: 24,
        eggs: 6,
        resources: 14,
        cards: 0,
        objectives: 19,
        misc: 1,
      },
      {
        playerId: 1,
        gameId: 9,
        guild: 6,
        dragons: 46,
        endGame: 26,
        eggs: 3,
        resources: 12,
        cards: 7,
        objectives: 12,
        misc: 1,
      },
      {
        playerId: 2,
        gameId: 9,
        guild: 11,
        dragons: 40,
        endGame: 16,
        eggs: 5,
        resources: 2,
        cards: 7,
        objectives: 19,
        misc: 0,
      },
      {
        playerId: 1,
        gameId: 10,
        guild: 15,
        dragons: 48,
        endGame: 23,
        eggs: 12,
        resources: 6,
        cards: 5,
        objectives: 22,
        misc: 0,
      },
      {
        playerId: 2,
        gameId: 10,
        guild: 6,
        dragons: 49,
        endGame: 22,
        eggs: 5,
        resources: 2,
        cards: 12,
        objectives: 11,
        misc: 1,
      },
      {
        playerId: 1,
        gameId: 11,
        guild: 6,
        dragons: 35,
        endGame: 8,
        eggs: 3,
        resources: 0,
        cards: 9,
        objectives: 13,
        misc: 2,
      },
      {
        playerId: 2,
        gameId: 11,
        guild: 9,
        dragons: 31,
        endGame: 9,
        eggs: 11,
        resources: 7,
        cards: 8,
        objectives: 19,
        misc: 3,
      },
      {
        playerId: 1,
        gameId: 12,
        guild: 6,
        dragons: 36,
        endGame: 13,
        eggs: 18,
        resources: 7,
        cards: 7,
        objectives: 12,
        misc: 2,
      },
      {
        playerId: 2,
        gameId: 12,
        guild: 6,
        dragons: 29,
        endGame: 3,
        eggs: 11,
        resources: 8,
        cards: 1,
        objectives: 15,
        misc: 1,
      },
      {
        playerId: 1,
        gameId: 13,
        guild: 16,
        dragons: 37,
        endGame: 14,
        eggs: 8,
        resources: 8,
        cards: 4,
        objectives: 22,
        misc: 1,
      },
      {
        playerId: 2,
        gameId: 13,
        guild: 8,
        dragons: 34,
        endGame: 10,
        eggs: 17,
        resources: 2,
        cards: 6,
        objectives: 14,
        misc: 0,
      },
      {
        playerId: 1,
        gameId: 14,
        guild: 12,
        dragons: 40,
        endGame: 7,
        eggs: 3,
        resources: 4,
        cards: 7,
        objectives: 13,
        misc: 3,
      },
      {
        playerId: 2,
        gameId: 14,
        guild: 6,
        dragons: 35,
        endGame: 18,
        eggs: 11,
        resources: 0,
        cards: 11,
        objectives: 19,
        misc: 0,
      },
      {
        playerId: 1,
        gameId: 15,
        guild: 6,
        dragons: 47,
        endGame: 3,
        eggs: 12,
        resources: 9,
        cards: 14,
        objectives: 16,
        misc: 0,
      },
      {
        playerId: 2,
        gameId: 15,
        guild: 10,
        dragons: 44,
        endGame: 5,
        eggs: 16,
        resources: 9,
        cards: 15,
        objectives: 16,
        misc: 3,
      },
      {
        playerId: 1,
        gameId: 16,
        guild: 15,
        dragons: 35,
        endGame: 4,
        eggs: 2,
        resources: 6,
        cards: 3,
        objectives: 15,
        misc: 3,
      },
      {
        playerId: 2,
        gameId: 16,
        guild: 15,
        dragons: 38,
        endGame: 7,
        eggs: 7,
        resources: 11,
        cards: 3,
        objectives: 22,
        misc: 2,
      },
      {
        playerId: 1,
        gameId: 17,
        guild: 10,
        dragons: 47,
        endGame: 10,
        eggs: 11,
        resources: 17,
        cards: 0,
        objectives: 19,
        misc: 0,
      },
      {
        playerId: 2,
        gameId: 17,
        guild: 22,
        dragons: 37,
        endGame: 8,
        eggs: 8,
        resources: 2,
        cards: 21,
        objectives: 16,
        misc: 1,
      },
      {
        playerId: 1,
        gameId: 18,
        guild: 48,
        dragons: 41,
        endGame: 22,
        eggs: 4,
        resources: 1,
        cards: 13,
        objectives: 19,
        misc: 2,
      },
      {
        playerId: 2,
        gameId: 18,
        guild: 41,
        dragons: 41,
        endGame: 9,
        eggs: 4,
        resources: 17,
        cards: 1,
        objectives: 19,
        misc: 2,
      },
    ],
    skipDuplicates: true,
  });

  console.log(`✅ Seeded ${scores.count} scores!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
